events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;

        location /api/v1/rooms {
            set $rooms_upstream svc-rooms:8081;
            proxy_pass http://$rooms_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/reservations {
            set $reservations_upstream svc-reservations:8082;
            proxy_pass http://$reservations_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
